"""Domain snapshots and structural topology; no authoritative transition execution."""

from .actors import ActorIdentity, ActorType
from .candidate_refs import ArtifactRef, EvidenceRef
from .completion import CompletionPolicyRef
from .effect import (
    EFFECT_CREATION_STATES,
    Effect,
    EffectDeduplicationRef,
    EffectExternalOperationRef,
    EffectOrigin,
    EffectPayloadRef,
    EffectState,
    EffectTargetRef,
    ObservedEffectOrigin,
    PlannedEffectOrigin,
    can_effect_transition,
)
from .effect_attribution import (
    EffectAttributionRecord,
    can_attach_effect_attribution,
    can_follow_effect_attribution,
)
from .effect_authorization import (
    EffectAuthorizationFindingRecord,
    EffectAuthorizationStatus,
    can_attach_effect_authorization_finding,
    can_follow_effect_authorization_finding,
)
from .effect_execution import (
    EffectExecutionAuthorizationRecord,
    EffectPreparationRecord,
    EffectVerificationRecord,
    can_attach_effect_preparation_record,
    can_authorize_effect_preparation,
    can_use_effect_verification_for_authorization,
    can_verify_effect_preparation,
)
from .effect_governance import (
    EffectGovernanceFindingRecord,
    EffectGovernancePolicyRef,
    EffectGovernanceStatus,
    can_attach_effect_governance_finding,
    can_follow_effect_governance_finding,
)
from .effect_incident import (
    EffectIncidentRecord,
    EffectIncidentStatus,
    can_attach_effect_incident_record,
    can_follow_effect_incident_record,
)
from .effect_observation import (
    EffectObservationRecord,
    EffectOccurrenceStatus,
    can_attach_effect_observation,
    can_follow_effect_observation,
)
from .effect_remediation import (
    EffectCompensationCompletionRecord,
    EffectCompensationPlanRecord,
    EffectRollbackRecord,
    can_attach_effect_rollback_record,
    can_complete_effect_compensation_plan,
)
from .errors import (
    CompletionPolicyNotSatisfied,
    ConcurrencyConflict,
    DomainError,
    EntityNotFound,
    ImmutableRecordViolation,
    InvalidDomainValue,
    InvalidRelationship,
    InvalidTransition,
    InvariantViolation,
    UnauthorizedTransition,
)
from .evaluation import (
    EVALUATION_CREATION_STATE,
    Evaluation,
    EvaluationState,
    can_evaluation_transition,
)
from .evaluation_arbitration import (
    ArbitrationDisposition,
    EvaluationArbitrationMemberDecision,
    EvaluationArbitrationPolicyRef,
    EvaluationArbitrationRecord,
    can_arbitrate_evaluation_conflict_set,
)
from .evaluation_conflict import (
    EvaluationConflictMemberRef,
    EvaluationConflictScopeRef,
    EvaluationConflictSetRecord,
    EvaluationConflictSetRef,
    can_extend_evaluation_conflict_set,
)
from .evaluation_effective_use import (
    EvaluationEffectiveUseView,
    derive_evaluation_effective_use,
)
from .evaluation_invalidation import (
    EvaluationInvalidationRecord,
    can_invalidate_evaluation,
)
from .evaluation_result import (
    EvaluationConfidence,
    EvaluationMethodRef,
    EvaluationResult,
    EvaluationVerdict,
)
from .evaluation_target import EvaluationTargetRef
from .execution_profile import ExecutionProfileRef
from .ids import (
    ActorId,
    CorrelationId,
    EffectAttributionId,
    EffectAuthorizationFindingId,
    EffectCompensationCompletionId,
    EffectCompensationPlanId,
    EffectExecutionAuthorizationId,
    EffectGovernanceFindingId,
    EffectId,
    EffectIncidentId,
    EffectIncidentRecordId,
    EffectObservationId,
    EffectPreparationRecordId,
    EffectRollbackRecordId,
    EffectVerificationRecordId,
    EvaluationArbitrationId,
    EvaluationConflictSetId,
    EvaluationId,
    EvaluationInvalidationId,
    ObjectiveId,
    OutcomeId,
    RunId,
    TaskId,
)
from .objective import (
    OBJECTIVE_CREATION_STATE,
    Objective,
    ObjectiveState,
    can_objective_transition,
)
from .outcome import (
    OUTCOME_CREATION_STATE,
    Outcome,
    OutcomeState,
    can_outcome_transition,
)
from .run import RUN_CREATION_STATE, Run, RunState, can_run_transition
from .task import TASK_CREATION_STATE, Task, TaskState, can_task_transition
from .time import Timestamp
from .transitions import TransitionReason
from .version import ConflictSetVersion, EntityVersion

__all__ = [
    "EFFECT_CREATION_STATES",
    "EVALUATION_CREATION_STATE",
    "OBJECTIVE_CREATION_STATE",
    "OUTCOME_CREATION_STATE",
    "RUN_CREATION_STATE",
    "TASK_CREATION_STATE",
    "ActorId",
    "ActorIdentity",
    "ActorType",
    "ArbitrationDisposition",
    "ArtifactRef",
    "CompletionPolicyNotSatisfied",
    "CompletionPolicyRef",
    "ConflictSetVersion",
    "ConcurrencyConflict",
    "CorrelationId",
    "DomainError",
    "Effect",
    "EffectAttributionId",
    "EffectAttributionRecord",
    "EffectAuthorizationFindingId",
    "EffectAuthorizationFindingRecord",
    "EffectAuthorizationStatus",
    "EffectCompensationCompletionId",
    "EffectCompensationCompletionRecord",
    "EffectCompensationPlanId",
    "EffectCompensationPlanRecord",
    "EffectDeduplicationRef",
    "EffectExternalOperationRef",
    "EffectExecutionAuthorizationId",
    "EffectExecutionAuthorizationRecord",
    "EffectId",
    "EffectGovernanceFindingId",
    "EffectGovernanceFindingRecord",
    "EffectGovernancePolicyRef",
    "EffectGovernanceStatus",
    "EffectIncidentId",
    "EffectIncidentRecord",
    "EffectIncidentRecordId",
    "EffectIncidentStatus",
    "EffectObservationId",
    "EffectObservationRecord",
    "EffectOccurrenceStatus",
    "EffectOrigin",
    "EffectPayloadRef",
    "EffectPreparationRecord",
    "EffectPreparationRecordId",
    "EffectRollbackRecord",
    "EffectRollbackRecordId",
    "EffectState",
    "EffectTargetRef",
    "EffectVerificationRecord",
    "EffectVerificationRecordId",
    "EntityNotFound",
    "EntityVersion",
    "Evaluation",
    "EvaluationArbitrationId",
    "EvaluationArbitrationMemberDecision",
    "EvaluationArbitrationPolicyRef",
    "EvaluationArbitrationRecord",
    "EvaluationConfidence",
    "EvaluationConflictMemberRef",
    "EvaluationConflictScopeRef",
    "EvaluationConflictSetId",
    "EvaluationConflictSetRecord",
    "EvaluationConflictSetRef",
    "EvaluationEffectiveUseView",
    "EvaluationId",
    "EvaluationInvalidationId",
    "EvaluationInvalidationRecord",
    "EvaluationMethodRef",
    "EvaluationResult",
    "EvaluationState",
    "EvaluationTargetRef",
    "EvaluationVerdict",
    "EvidenceRef",
    "ExecutionProfileRef",
    "ImmutableRecordViolation",
    "InvalidDomainValue",
    "InvalidRelationship",
    "InvalidTransition",
    "InvariantViolation",
    "Objective",
    "ObjectiveId",
    "ObjectiveState",
    "Outcome",
    "OutcomeId",
    "OutcomeState",
    "ObservedEffectOrigin",
    "PlannedEffectOrigin",
    "Run",
    "RunId",
    "RunState",
    "Task",
    "TaskId",
    "TaskState",
    "Timestamp",
    "TransitionReason",
    "UnauthorizedTransition",
    "can_arbitrate_evaluation_conflict_set",
    "can_extend_evaluation_conflict_set",
    "can_evaluation_transition",
    "can_attach_effect_observation",
    "can_attach_effect_preparation_record",
    "can_attach_effect_rollback_record",
    "can_attach_effect_attribution",
    "can_attach_effect_authorization_finding",
    "can_attach_effect_governance_finding",
    "can_attach_effect_incident_record",
    "can_effect_transition",
    "can_complete_effect_compensation_plan",
    "can_authorize_effect_preparation",
    "can_follow_effect_observation",
    "can_follow_effect_attribution",
    "can_follow_effect_authorization_finding",
    "can_follow_effect_governance_finding",
    "can_follow_effect_incident_record",
    "can_invalidate_evaluation",
    "can_use_effect_verification_for_authorization",
    "can_verify_effect_preparation",
    "derive_evaluation_effective_use",
    "can_objective_transition",
    "can_outcome_transition",
    "can_run_transition",
    "can_task_transition",
]
